### ISSUE TITLE
Clicking on reports give error 500

### ISSUE THREAD

**Issue by xBounceIT** [anuko/timetracker#135]
On v1.22.21.5812 when clicking Reports the browser gives a white page and this logs appear:

PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /var/www/html/timetracker/WEB-INF/lib/form/MultipleSelectCombobox.class.php:81\nStack trace:\n#0 /var/www/html/timetracker/WEB-INF/lib/form/MultipleSelectCombobox.class.php(81): in_array()\n#1 /var/www/html/timetracker/WEB-INF/lib/form/FormElement.class.php(77): MultipleSelectCombobox->getHtml()\n#2 /var/www/html/timetracker/WEB-INF/lib/form/Form.class.php(193): FormElement->toArray()\n#3 /var/www/html/timetracker/reports.php(534): Form->toArray()\n#4 {main}\n  thrown in /var/www/html/timetracker/WEB-INF/lib/form/MultipleSelectCombobox.class.php on line 81, referer: /time.php

Unfortunately i don't seem to be able to replicate it on the demo online but i will keep trying.

**Comment by xBounceIT** [comment]
I can confirm with 1.22.22.5813 that the issue is solved.
